# Generated by Django 5.2.4 on 2025-07-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0002_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='duracion_semanas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
